#
# Copyright (C) 2015 MEIZU Technology
#
# Performance Boost Configuration
# Provides configure for scenario boost
#
# Author: caobo@Shell@PerformanceTeam
# Format:
# scenarioname=priority timeout cpu_core cpu_freq gpu_feq
#
# Be Attention: The lower the value of the priority, the
#      higher the priority which will not be interrupted.
#
#BigLittleArchitecture=false
AppStart=0 1000 4 1300000 0
AppSwitch=1 500 4 1300000 0
WindowAnimation=10 2000 4 1300000 0
KeyBoost=20 1000 4 1300000 0
AppInstall=30 3000 4 1300000 0
AppUninstall=30 3000 4 1300000 0
TouchBoost=40 2000 4 1300000 0
ObtainView=20 1000 4 1300000 0
FlingBoost=20 1000 4 1300000 0
