LOCAL_APTH := $(call my-dir)
iclude $(CLEAR_VARS)

LOCAL_MODULE := CPL
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := CPL.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILIGED_MODULE := true

include $(BUILD_PREBUILT)