# Display
USE_OPENGL_RENDERER := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
MAX_VIRTUAL_DISPLAY_DIMENSION := 1
PRESENT_TIME_OFFSET_FROM_VSYNC_NS := 0
TARGET_USES_ION := true

MTK_HWC_SUPPORT := yes
MTK_HWC_VERSION := 1.4.1

MTK_GPU_VERSION := mali midgard r7p0

# Live Display
TARGET_HAS_LEGACY_DISPLAY_SERVICES := true
