LOCAL_PATH := device/meizu/m5c

# Kernel
TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/rootdir/kernel

BOARD_KERNEL_BASE = 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET = 0x03f88000
BOARD_TAGS_OFFSET = 0x0df88000
BOARD_KERNEL_OFFSET = 0x00080000

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
BOARD_KERNEL_CMDLINE = bootopt=64S3,32N2,64N2 androidboot.selinux=permissive

TARGET_USES_64_BIT_BINDER := true

BOARD_MKBOOTIMG_ARGS := --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --board mt6737

BOARD_CUSTOM_BOOTIMG := true

TARGET_KMODULES := true
